---
driver_plugin: vagrant

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box
    require_chef_omnibus: true
    customize:
      memory: 512
    network:
    # Allow access to the Jenkins webui which is useful when troubleshooting
    - - forwarded_port
      - guest: 8080
        host: 9090
        auto_correct: true
  run_list: ["recipe[apt]"]

- name: debian-6.0.8
  driver_config:
    box: opscode-debian-6.0.8
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_debian-6.0.8_chef-provisionerless.box
    require_chef_omnibus: true
    customize:
      memory: 512
  run_list: ["recipe[apt]"]

suites:
- name: default
  run_list: ["recipe[kitchen-jenkins]"]
  attributes: {}
